### ISSUE TITLE
Buy www.minimum-reproduction.wtf

### ISSUE THREAD

**Issue by BrunnerLivio** [jmcdo29/wtf-is-a-minimum-reproduction#1]
If you have spare Christmas money ... because `.wtf` domains are fun 🕺 

https://domains.google.com/registrar/search?searchTerm=minimum-reproduction.wtf&hl=en&_ga=2.221661272.1584197111.1607969797-512408089.1597397271#

**Comment by BrunnerLivio** [comment]
btw. isn't it called minimal reproduction? :P

**Comment by jmcdo29** [comment]
> btw. isn't it called minimal reproduction? :P

I use "minimum reproduction" personally, but both get the same point across.

**Comment by jmcdo29** [comment]
I'll absolutely look into buying that come the new year

**Comment by jmcdo29** [comment]
Is been done. Should be up and properly running within the next day or two at [minimum-reproduction.wtf](https://minimum-reproduction.wtf)
![Screenshot_20210105-185117](https://user-images.githubusercontent.com/28268680/103723525-24b5b700-4f87-11eb-9647-4b85bbc31d27.png)
